# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 4.1.1
_src_path: gh:epics-containers/deployment-template-argocd
argocd_project: p99
argocd_server: argocd.diamond.ac.uk
cluster_name_apps: p99-beamline
cluster_name_services: p99-beamline
cluster_namespace_apps: p99-beamline
cluster_namespace_services: p99-beamline
deployment_repo: https://github.com/epics-containers/p99-deployment
description: p99 IOC Instances and Services
git_platform: github.com
github_org: epics-containers
ioc_group: p99
logging_url: https://graylog2.diamond.ac.uk/search?rangetype=relative&fields=message%2Csource&width=1489&highlightMessage=&relative=172800&q=pod_name%3A{service_name}*
services_release: 2024.1.1
services_repo: https://github.com/epics-containers/p99-services
